# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=15, unique=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('pubdate', models.CharField(max_length=10)),
            ],
        ),
    ]
