# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170717_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-07-17'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
