# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_wishbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishbook',
            name='wish_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
