# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170718_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='책소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='할인가격'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, verbose_name='표지이미지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=25, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN(13자리)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, verbose_name='원본링크'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.CharField(blank=True, max_length=10, verbose_name='출판일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='출판사'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='대여 종료일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='대여 시작일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대출회원'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='도서명'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='author',
            field=models.CharField(max_length=100, verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='책소개'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='할인가격'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='image',
            field=models.URLField(blank=True, verbose_name='표지이미지'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='isbn',
            field=models.CharField(max_length=50, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='isbn13',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISBN(13자리)'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='link',
            field=models.URLField(blank=True, verbose_name='원본링크'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='pubdate',
            field=models.CharField(blank=True, max_length=10, verbose_name='출판일'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='출판사'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='title',
            field=models.CharField(max_length=100, verbose_name='도서명'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='wish_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매 신청자'),
        ),
    ]
