# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_auto_20170719_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateField(verbose_name='대여시작일')),
                ('rent_end', models.DateField(verbose_name='대여종료일')),
                ('return_status', models.BooleanField(verbose_name='반납여부')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='반납일')),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='rent_end',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rent_start',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rent_user',
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='renthistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='대출도서'),
        ),
        migrations.AddField(
            model_name='renthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대출회원'),
        ),
        migrations.AddField(
            model_name='book',
            name='rent_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.RentHistory', verbose_name='대출정보'),
        ),
    ]
