# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_renthistory_sent_overdue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='도서명'),
        ),
    ]
