# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, verbose_name='소개'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2017-07-17', verbose_name='가입일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='선택사항', upload_to='accounts/avatar/', verbose_name='프로필 사진'),
        ),
    ]
